In [78]:
import seaborn as sns;
import matplotlib.pyplot as plt;
import pandas as pd;
import numpy as np;
from sklearn.model_selection import train_test_split;
from sklearn.linear_model import LogisticRegression; 

import os;
import time;
import datetime;
%matplotlib inline

In [79]:
%ls

'merged_total_census_party (1).csv'   sample_data/


In [80]:
df = pd.read_csv('merged_total_census_party (1).csv').drop(columns = 'Unnamed: 0')

In [81]:
df.head()

Counties  Year time_period Under 5 years 5 to 9 years  \
0     Colusa County (5 YR)  2016          5Y         7.40%        7.80%   
1     Colusa County (5 YR)  2012          5Y         7.40%        7.80%   
2         Glenn County, CA  2016          5Y         8.60%        8.40%   
3         Glenn County, CA  2012          5Y         7.30%        7.10%   
4  Del Norte County (5 YR)  2016          5Y         7.50%        6.40%   

  10 to 14 years 15 to 19 years 20 to 24 years 25 to 29 years 30 to 34 years  \
0          8.10%          7.20%          6.90%          6.60%          6.40%   
1          8.10%          7.20%          6.90%          6.60%          6.40%   
2          7.50%          8.40%          6.00%          6.40%          6.00%   
3          8.00%          7.10%          6.70%          6.10%          6.00%   
4          9.00%          7.40%          7.00%          6.20%          4.90%   

   ... 55 to 59 years 60 to 64 years 65 to 69 years 70 to 74 years  \
0  ...          6.60%          5.60%          4.50%          3.30%   
1  ...          6.60%          5.60%          4.50%          3.30%   
2  ...          5.40%          5.50%          4.30%          2.20%   
3  ...          6.30%          6.40%          5.00%          3.10%   
4  ...          5.80%          5.60%          4.20%          3.00%   

  75 to 79 years 80 to 84 years 85 years and over winning_candidate  \
0          2.40%          1.80%             1.00%      Donald Trump   
1          2.40%          1.80%             1.00%       Mitt Romney   
2          1.70%          2.40%             1.30%      Donald Trump   
3          2.80%          1.80%             1.90%       Mitt Romney   
4          2.00%          2.00%             2.00%      Donald Trump   

  winner_vote_percent      ideological_label  
0                53.5  Populist Conservative  
1                59.7           Conservative  
2                61.1  Populist Conservative  
3                61.1           Conservative  
4                53.7  Populist Conservative  

[5 rows x 24 columns]

In [82]:
df['ideological_label'].value_counts()

Liberal                  31
Conservative             28
Liberal/Progressive      27
Populist Conservative    24
Name: ideological_label, dtype: int64

## Select Model and Train

In [83]:
from tqdm import tqdm

In [90]:
model = LogisticRegression(multi_class='multinomial', max_iter= 1000)

In [85]:
# converting percent strings into raw floating point numbers

for i in tqdm(df.iloc[:, 7:-3].columns):
  df[i] = df[i].apply(lambda x : float(x[:-1]))
df.head()

100%|██████████| 14/14 [00:00<00:00, 1315.92it/s]


Counties  Year time_period Under 5 years 5 to 9 years  \
0     Colusa County (5 YR)  2016          5Y         7.40%        7.80%   
1     Colusa County (5 YR)  2012          5Y         7.40%        7.80%   
2         Glenn County, CA  2016          5Y         8.60%        8.40%   
3         Glenn County, CA  2012          5Y         7.30%        7.10%   
4  Del Norte County (5 YR)  2016          5Y         7.50%        6.40%   

  10 to 14 years 15 to 19 years  20 to 24 years  25 to 29 years  \
0          8.10%          7.20%             6.9             6.6   
1          8.10%          7.20%             6.9             6.6   
2          7.50%          8.40%             6.0             6.4   
3          8.00%          7.10%             6.7             6.1   
4          9.00%          7.40%             7.0             6.2   

   30 to 34 years  ...  55 to 59 years  60 to 64 years  65 to 69 years  \
0             6.4  ...             6.6             5.6             4.5   
1             6.4  ...             6.6             5.6             4.5   
2             6.0  ...             5.4             5.5             4.3   
3             6.0  ...             6.3             6.4             5.0   
4             4.9  ...             5.8             5.6             4.2   

   70 to 74 years  75 to 79 years  80 to 84 years  85 years and over  \
0             3.3             2.4             1.8                1.0   
1             3.3             2.4             1.8                1.0   
2             2.2             1.7             2.4                1.3   
3             3.1             2.8             1.8                1.9   
4             3.0             2.0             2.0                2.0   

   winning_candidate  winner_vote_percent      ideological_label  
0       Donald Trump                 53.5  Populist Conservative  
1        Mitt Romney                 59.7           Conservative  
2       Donald Trump                 61.1  Populist Conservative  
3        Mitt Romney                 61.1           Conservative  
4       Donald Trump                 53.7  Populist Conservative  

[5 rows x 24 columns]

In [86]:
df.iloc[:, 7:-3]

20 to 24 years  25 to 29 years  30 to 34 years  35 to 39 years  \
0               6.9             6.6             6.4             6.3   
1               6.9             6.6             6.4             6.3   
2               6.0             6.4             6.0             5.9   
3               6.7             6.1             6.0             5.3   
4               7.0             6.2             4.9             5.8   
..              ...             ...             ...             ...   
105             6.4             6.5             6.5             6.0   
106             7.3             6.5             6.4             6.5   
107             6.9             6.6             6.2             6.5   
108             7.3             8.3             8.0             6.7   
109             7.7             8.2             7.2             5.9   

     40 to 44 years  45 to 49 years  50 to 54 years  55 to 59 years  \
0               5.5             6.1             6.6             6.6   
1               5.5             6.1             6.6             6.6   
2               6.9             6.4             6.6             5.4   
3               6.5             5.8             6.8             6.3   
4               6.8             6.9             7.4             5.8   
..              ...             ...             ...             ...   
105             6.3             6.5             7.3             7.3   
106             6.4             7.1             7.5             6.6   
107             7.0             7.5             7.4             6.1   
108             5.1             5.4             6.2             5.9   
109             6.0             5.7             6.2             6.4   

     60 to 64 years  65 to 69 years  70 to 74 years  75 to 79 years  \
0               5.6             4.5             3.3             2.4   
1               5.6             4.5             3.3             2.4   
2               5.5             4.3             2.2             1.7   
3               6.4             5.0             3.1             2.8   
4               5.6             4.2             3.0             2.0   
..              ...             ...             ...             ...   
105             7.3             6.1             3.9             2.6   
106             5.3             4.2             2.7             2.2   
107             5.3             3.8             2.5             2.1   
108             6.1             5.2             1.7             1.4   
109             4.9             4.4             2.6             1.9   

     80 to 84 years  85 years and over  
0               1.8                1.0  
1               1.8                1.0  
2               2.4                1.3  
3               1.8                1.9  
4               2.0                2.0  
..              ...                ...  
105             1.9                2.3  
106             1.6                1.9  
107             1.7                1.7  
108             1.0                1.5  
109             1.3                1.3  

[110 rows x 14 columns]

In [87]:
X = df.iloc[:, 7:-3]
y = df.iloc[:, -1]

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [91]:
model.fit (X_train, y_train)

LogisticRegression(max_iter=1000, multi_class='multinomial')

## Model Evaluation

In [92]:
y_pred = model.predict(X_test);

In [93]:
from sklearn.metrics import confusion_matrix, classification_report;

In [94]:
print ("Confusion Matrix: ", confusion_matrix(y_test, y_pred), "\n");
print ("Classification Report: ", classification_report(y_test, y_pred), "\n");

Confusion Matrix:  [[0 3 5 4]
 [0 5 2 1]
 [0 7 0 1]
 [1 2 4 2]] 

Classification Report:                         precision    recall  f1-score   support

         Conservative       0.00      0.00      0.00        12
              Liberal       0.29      0.62      0.40         8
  Liberal/Progressive       0.00      0.00      0.00         8
Populist Conservative       0.25      0.22      0.24         9

             accuracy                           0.19        37
            macro avg       0.14      0.21      0.16        37
         weighted avg       0.12      0.19      0.14        37
 



## Random Forest

In [47]:
from sklearn.ensemble import RandomForestClassifier;

In [95]:
model_rf = RandomForestClassifier();

In [96]:
model_rf.fit(X_train, y_train)

RandomForestClassifier()

In [97]:
y_pred_rf = model_rf.predict(X_test);
y_pred_rf_train = model_rf.predict(X_train);

In [98]:
print ("Confusion Matrix: ", confusion_matrix(y_test, y_pred_rf), "\n");
print ("Classification Report: ", classification_report(y_test, y_pred_rf), "\n");

Confusion Matrix:  [[1 2 7 2]
 [0 4 3 1]
 [0 4 3 1]
 [4 1 1 3]] 

Classification Report:                         precision    recall  f1-score   support

         Conservative       0.20      0.08      0.12        12
              Liberal       0.36      0.50      0.42         8
  Liberal/Progressive       0.21      0.38      0.27         8
Populist Conservative       0.43      0.33      0.38         9

             accuracy                           0.30        37
            macro avg       0.30      0.32      0.30        37
         weighted avg       0.29      0.30      0.28        37
 



In [99]:
print ("Confusion Matrix: ", confusion_matrix(y_train, y_pred_rf_train), "\n");
print ("Classification Report: ", classification_report(y_train, y_pred_rf_train), "\n");

Confusion Matrix:  [[16  0  0  0]
 [ 0 23  0  0]
 [ 0  0 19  0]
 [ 0  0  0 15]] 

Classification Report:                         precision    recall  f1-score   support

         Conservative       1.00      1.00      1.00        16
              Liberal       1.00      1.00      1.00        23
  Liberal/Progressive       1.00      1.00      1.00        19
Populist Conservative       1.00      1.00      1.00        15

             accuracy                           1.00        73
            macro avg       1.00      1.00      1.00        73
         weighted avg       1.00      1.00      1.00        73
 



In [100]:
#len(model_rf.feature_importances_)
#len(X.columns)
for i in range(len(X.columns)):
  print (X.columns[i], ": ", model_rf.feature_importances_[i], "\n")

20 to 24 years :  0.05272565779685817 

25 to 29 years :  0.0595630257431633 

30 to 34 years :  0.05505648677311639 

35 to 39 years :  0.07710415586271453 

40 to 44 years :  0.08462712580046682 

45 to 49 years :  0.07248662928560896 

50 to 54 years :  0.08291625153169269 

55 to 59 years :  0.07597244153671133 

60 to 64 years :  0.07469790755987278 

65 to 69 years :  0.07541655982845687 

70 to 74 years :  0.0789523352450975 

75 to 79 years :  0.08812980069773715 

80 to 84 years :  0.05680205150732393 

85 years and over :  0.06554957083117967 



## Neural networks

In [66]:
import tensorflow as tf
from tensorflow.keras import layers

In [75]:
#deep_cols = []
#for i in range(len(X.columns)):
  #deep_cols.append(tf.feature_column.indicator_column(tf.feature_column.numeric_column(X.columns[i])))


model_NN = tf.keras.Sequential([
  #layers.Dense(INPUT_LAYER, activation='relu'),  ### FI ME: Look into this based on data being used
  layers.Dense(512, activation='relu'),
  layers.Dense(256, activation='relu'),
  layers.Dropout(0.2),
  layers.Dense(128, activation='relu'),
  layers.Dense(64, activation='relu'),
  layers.Dense(1, activation='tanh')
])

model_NN.compile(optimizer=tf.keras.optimizers.Adam(),  
              #loss=tf.keras.losses.CategoricalCrossentropy(),
              loss=tf.keras.losses.BinaryCrossentropy(),              
              metrics=['accuracy', 'Recall', 'Precision', 'AUC'])

In [77]:
model_NN.fit(x = X_train, y = y_train, epochs = 50, verbose = 2)

Epoch 1/50


UnimplementedError: ignored